# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hix_bro3?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: orgtec
    hikari:
      pool-name: DatebookHikariCP
      minimum-idle: 3
      auto-commit: true
      idle-timeout: 10000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    #      naming:
    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        # 方言支持物理空间
        dialect: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
# Logger Config
logging:
  level:
    cn.orgtec.hix.broadcast.repository: debug

  jackson:
    default-property-inclusion: non_null

hbase:
  zk:
    host: hix-virtual-machine
    port: 2181





